services:
    frontend:
        build: 
            context: ./frontend
            dockerfile: Dockerfile
        container_name: front_ecosynthesia
        volumes:
            - ./frontend:/app          
            - /app/node_modules        
        working_dir: /app   
        ports:
            - "5174:5173"
        networks:
            - ecosynthesia-network

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: back_ecosynthesia
        volumes:
            - ./backend:/app          
            - ./bucket:/app/bucket    
        working_dir: /app
        depends_on:
            - ia_service  
        links:                       
        - ia_service:ia_ecosynthesia
        ports:
            - "3001:3000"
        environment:
            - NODE_ENV=development
            - POSTGRES_HOST=host.docker.internal  
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - IA_SERVICE_URL=http://ia_ecosynthesia:8000
        extra_hosts:
            - "host.docker.internal:host-gateway" 
        networks:
            - ecosynthesia-network

    ia_service:
        build:
            context: ./ia_service
            dockerfile: Dockerfile
        container_name: ia_ecosynthesia
        volumes:
            - ./ia_service:/app
            - ./bucket:/app/bucket     
        working_dir: /app   
        ports:
            - "8001:8000"
        environment:
            - PROJECT_ROOT=/
            - OLLAMA_URL=http://host.docker.internal:11434
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - ecosynthesia-network

networks:
    ecosynthesia-network:
        driver: bridge      